openapi: 3.0.1
info:
  title: API de consultório
  description: API para controlar médicos e suas especialidades dentro do consultório.
  version: 0.0.1
  termsOfService: https/mockapi.io
  contact: 
    name: Suporte a Devs
    email: contato@example.com
    url: https/mockapi.io
  license:
    name: "Licença GPLv3"
    url: https://www.gnu.org/licenses/gpl-3.0.html
externalDocs:
    description: Documentação Burocrática
    url: https/mockapi.io
servers:
- url: https://6096015d116f3f00174b29ba.mockapi.io/
  description: API de Teste
paths:
  /especialidades:
    get:
      summary: Recupera todas as especialidades
      responses:
        200:
          $ref: "#/components/responses/200"
    post:
      summary: Cria nova especialidade
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                descricao:
                  type: string
      responses:
        201:
          $ref: "#/components/responses/201"
  /especialidades/{id}:
    parameters:
    - name: id
      in: path
      schema:
        type: integer
      required: true 
    get:
      summary: Recuperando uma entidade pelo ID  
      responses:
        200:
         $ref: "#/components/responses/200"
        404:
          $ref: "#/components/responses/404"
    put:
      summary: Alterar descrição da especialidade
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                descricao:
                  type: string
      responses:
        200:
          $ref: "#/components/responses/200"
        404:
          $ref: "#/components/responses/404"
    delete:
      summary: Alterar descrição da especialidade
      responses:
        200:
          $ref: "#/components/responses/200"
        404:
         $ref: "#/components/responses/404"
security:
  - auth: []
components:
  schemas:
    especialidade:
      type: object
      properties: 
        id: 
          type: integer
        descricao:
          type: string
  responses:        
    200:
      description: Sucesso
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/especialidade"
    201:
      description: Created
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/especialidade"  
    404:
          description: ID ou Especialidade não encontrada
          content:
            application/json:
              example: "Not Found"
  securitySchemes:
    auth: 
      type: http
      scheme: bearer
      bearerFormat: JWT